# Generated by Django 5.0.7 on 2025-03-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_groups_account_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='usdt_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
