# Generated by Django 5.0.7 on 2025-03-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_forexplan_purchase_url_remove_forexplan_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/profile_pic.webp', null=True, upload_to='profile_pics/'),
        ),
    ]
