# Generated by Django 5.0.7 on 2025-03-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_transactioncodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='total_profits',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
